### PR TITLE
Moved to MIT license

### PR DESCRIPTION
**Pull request by glatard**
Discussions have been going on about the license to use in the Boutiques project. The conclusion is that the license should be as open as possible to allow for integration in as many platforms as possible. Therefore, we adopt the MIT license which is much less constrained than the GPL. 

The copyright holders are the institutions of the ones who committed to the project so far. The list will be extended as new contributions come.

@merous, @rafaelfsilva, could you review the text of the license and raise any potential objection?
@natacha-beck, @ttaa9: we need your approval to change the license too.

@chrisfilo, @kofalt, @johnflavin, @gsfr, @poquirion: do you have any objection?

### CODE REVIEW

**Comment by ttaa9** [comment]
Cool with me

**Comment by gsfr** [comment]
Good move!

**Comment by johnflavin** [comment]
Fine with me

**Comment by merous** [comment]
Looks good.
The actual legal name of McGill University is the rather long "The Royal Institution for the Advancement of Learning McGill University", which is what we use in our other licenses...

**Comment by glatard** [comment]
@merous: fixed.

**Comment by kofalt** [comment]
No objection on change.
You'll need sign-off from everyone who has contributed & it sounds like you're working on that :)

**Comment by natacha-beck** [comment]
No objection.

**Comment by rafaelfsilva** [comment]
It's completely fine with me.

**Comment by poquirion** [comment]
All good with me too.

**Pull request merged**
