### PR TITLE
[MAINT] transfer CI from Travis to github action

### LINKED ISSUE #633: More efficient test cleanups
## Purpose

Files created during pytest should be ignored by git.
Generated test files should be removed between tests regardless of tests passing.

## Context

Eliminate use of ./cleanup_tests.sh

## Possible Implementation (optional)

Create a test directory as test_dump for all files created during tests. Maybe wipe test_dump between each test so failing tests or interruptions don't leave test files.

## Related issues (optional)

#627

### PR DESCRIPTION
**Pull request by Remi-Gau**
## Related issues

- #670
- closes #633 

## Checklist

- [ ] Unit tests pass: **nope but at least now they are running**

## Purpose

Set up style checks and test with make, tox and some bash scripts to make it easier to run the same thing locally and in CI.

## Current behaviour

Tests and style checks were not running.

## New behaviour

Now they do... And some things are failing.
 
### Does this introduce a major change?

- [ ] Yes
- [x] No

## Implementation Detail

- Rely on tox for virtual environment set up to improve consistency.
- Add a pre-commit config to start enforcing some style checks at commit time.
  - also add workflow to update hooks every 3 months
- Add a pyproject.toml to host pytest configuration.
- Update the gitignore based on the template from github.
- Move the clean up script into the make file.
- set up dependabot to keep actions up to date

## TODO

- [x] set up testing matrix with more recent pythons and several os (expect issues when setting up docker and singularity on Mac and Windows)
- [x] do some light clean up of make file and tox
- [ ] investigate why tests are failing and either fix or mark as expected failure to fix later.
- [x] add coverall to gha: may not work if the github account of boutiques is not synched with coveralls
- [x] remove Travis.yml

### CODE REVIEW

**Comment by Remi-Gau** [comment]
Many tests are failing because of a 404 on this URL

```python
example_boutiques_tool = MockZenodoRecord(
        660699, "Example Boutiques Tool", filename="https://sandbox.zenodo.org/"
        "record/660699/files/example1_docker.json")

```

**Comment by Remi-Gau** [comment]
Some tests only fail for python >= 3.10

``
FAILED boutiques/tests/test_pprint.py::TestPPrint::test_categories_and_order - ValueError: substring not found
FAILED boutiques/tests/test_pprint.py::TestPPrint::test_input_optionality_separation - IndexError: list index out of range
``

**Comment by Remi-Gau** [comment]
> Some tests only fail for python >= 3.10
> 
> ```
> FAILED boutiques/tests/test_pprint.py::TestPPrint::test_categories_and_order - ValueError: substring not found
> FAILED boutiques/tests/test_pprint.py::TestPPrint::test_input_optionality_separation - IndexError: list index out of range
> ```

should be fixed

**Comment by Remi-Gau** [comment]
OK will move the pyporject.toml here because this setup is so antiquated there is no point trying to salvage it.

**Comment by Remi-Gau** [comment]
OK will mark the failing tests as XFAIL for now, so that we revisit them later because I am pretty sure that those test failings are not due to the changes here but more to the fact that the code may have been changed without running the tests in a while.

**Comment by mathdugre** [comment]
Most test seem to fail because the mocked zenodo id doesn't exist anymore. I think it might be because it was residing on the Zenodo sandbox, which can be reset anytime. We might want to have the mocked id on the production platform instead.
https://github.com/boutiques/boutiques/blob/2b8cf48d0905987321dfb780dc104c8ca85a5cf6/boutiques/tests/boutiques_mocks.py#L40-L42

Similarly, the Zenodo token might be expired. Creating a new one, and using it for the tests would solve this as well.
ps: we probably don't want to have it as clear text this time around 🙃 .

**Comment by Remi-Gau** [comment]
> we probably don't want to have it as clear text this time around

ha. yeah maybe not: or at least not right next to our AWS login info... (This is a joke)

**Comment by mathdugre** [comment]
@Remi-Gau , I went through the failed test and classified them into three categories for failure: Missing Zenodo sandbox record, Expired Zenodo ID, and Others.
I was thinking we can fix the first two categories and mark the other ones as XFAIL. We can tackle the XFAIL in another issue.


Failed test for `3.12`

# Missing sandbox record
- [ ] boutiques/tests/test_pull.py::TestPull::test_pull
- [ ] boutiques/tests/test_pull.py::TestPull::test_pull_duplicate_collapses
- [ ] boutiques/tests/test_pull.py::TestPull::test_pull_missing_raises_exception
- [ ] boutiques/tests/test_pull.py::TestPull::test_pull_multi
- [ ] boutiques/tests/test_simulate.py::TestSimulate::test_success_desc_from_zenodo
- [ ] boutiques/tests/test_test.py::TestTest::test_test_good_from_zenodo
- [ ] boutiques/tests/test_example1.py::TestExample1::test_example1_exec_docker_from_zenodo
- [ ] boutiques/tests/test_example1.py::TestExample1::test_example1_exec_docker_from_zenodo_debug
- [ ] boutiques/tests/test_example1.py::TestExample1::test_example1_exec_docker_from_zenodo_desc2func_default
- [ ] boutiques/tests/test_example1.py::TestExample1::test_example1_exec_docker_from_zenodo_desc2func_launch
- [ ] boutiques/tests/test_example1.py::TestExample1::test_example1_exec_docker_from_zenodo_desc2func_simNoInvoc
- [ ] boutiques/tests/test_example1.py::TestExample1::test_example1_exec_docker_from_zenodo_desc2func_simulate
- [ ] boutiques/tests/test_evaluate.py::TestEvaluate::test_evaloutput_from_zenodo
- [ ] boutiques/tests/test_data_collection.py::TestDataCollection::test_read_doi_zenodo


# Expired Zenodo ID
- [ ] boutiques/tests/test_publisher.py::TestPublisher::test_publisher_auth
- [ ] boutiques/tests/test_publisher.py::TestPublisher::test_publisher_auth_no_permission
- [ ] boutiques/tests/test_publisher.py::TestPublisher::test_publication
- [ ] boutiques/tests/test_publisher.py::TestPublisher::test_publication_replace_no_id
- [ ] boutiques/tests/test_publisher.py::TestPublisher::test_publication_replace_with_id
- [ ] boutiques/tests/test_publisher.py::TestPublisher::test_publication_toolname_forwardslash
- [ ] boutiques/tests/test_deprecate.py::TestDeprecate::test_deprecate
- [ ] boutiques/tests/test_deprecate.py::TestDeprecate::test_deprecate_by_inexistent
- [ ] boutiques/tests/test_deprecate.py::TestDeprecate::test_deprecate_deprecated
- [ ] boutiques/tests/test_deprecate.py::TestDeprecate::test_deprecate_no_by
- [ ] boutiques/tests/test_deprecate.py::TestDeprecate::test_deprecate_previous_version
- [ ] boutiques/tests/test_data_handler.py::TestDataHandler::test_publish_bulk
- [ ] boutiques/tests/test_data_handler.py::TestDataHandler::test_publish_individual
- [ ] boutiques/tests/test_data_handler.py::TestDataHandler::test_publish_single


# Mark as XFAIL for now
- [ ] boutiques/tests/test_prepare.py::TestPrepare::test_prepare_docker
- [ ] boutiques/tests/test_import.py::TestImport::test_docopt_import_valid
- [ ] boutiques/tests/test_import.py::TestImport::test_docopt_import_valid_options
- [ ] boutiques/tests/test_example1.py::TestExample1::test_example1_exec_singularity_force_docker
- [ ] boutiques/tests/test_data_collection.py::TestDataCollection::test_add_provenance
- [ ] boutiques/tests/test_data_collection.py::TestDataCollection::test_data_collection

**Comment by mathdugre** [comment]
We can use this new example record at https://zenodo.org/records/13913800 and the `ZENODO_TOKEN` GitHub secret.

**Comment by mathdugre** [comment]
For now, I'll merge these changes in a temporary branch. We can work on fix the test over there

**Comment by Remi-Gau** [comment]
Do you want me to try fixing them?

**Comment by mathdugre** [comment]
I worked a bit on it yesterday. The checklist above is now updated to reflect the latest changes on my branch [fix/test](https://github.com/mathdugre/boutiques/tree/fix/test).

Any help would be welcomed. Do you want to have a look at the failing test in the "Expired Zenodo ID" category? I could tackle the ones in the "Others / XFAIL" category in parallel.

**Comment by Remi-Gau** [comment]
> the latest changes on my branch [fix/test](https://github.com/mathdugre/boutiques/tree/fix/test)

can you open a PR to merge this in fix-ci?
I will have a look: may help me wrap my head around this
and we should probably run the tests on fix-ci because at the moment they do not

**Comment by mathdugre** [comment]
I opened the PR https://github.com/boutiques/boutiques/pull/684. Note that I had formatted the code with black line length 88 on this pr so I probably will have to rerun it depending on what standard we go for in #675 .

**Pull request merged**
