### PR TITLE
Fixed codestyle

### PR DESCRIPTION
**Pull request by erinb90**
Fixed the overindentation that the new version of pycodestyle was complaining about.

### CODE REVIEW

**Comment by glatard** [comment]
Hi @erinb90, shall we just run our tests with PyPy >= 5.4 and clear this issue?

**Comment by erinb90** [comment]
@glatard Yes I think we should.

**Comment by glatard** [comment]
perfect, would you like to do it as part of this PR?

**Comment by erinb90** [comment]
Can we merge this?

**Pull request merged**
