### PR TITLE
Fixes in BIDS importer

### PR DESCRIPTION
**Pull request by glatard**
* BIDS app import now doesn't crash if BIDS app has no 'version' file
* Removed tabs from template

### CODE REVIEW

**Comment by gkiar** [comment]
Cool - the first test fails due to indentation and the second due to what appears to be an out of date Zenodo ID for the test. Once those are fixed I'm happy to merge :)

**Comment by erinb90** [comment]
> Cool - the first test fails due to indentation and the second due to what appears to be an out of date Zenodo ID for the test. Once those are fixed I'm happy to merge :)

@gkiar The Zenodo publication test fails sporadically because of their API being unstable. #289 intends to fix this.

**Comment by gkiar** [comment]
@erinb90 yea, I've noticed that, but here's it was an `AssertionError` that two IDs didn't match - is this also caused by the same thing?

**Comment by glatard** [comment]
@gkiar are you ok to merge this now?

**Comment by gkiar** [comment]
Yep! Sorry about the delay.

**Pull request merged**
